### ISSUE TITLE
路由器中部署后，使用cloudflare tunnel内网穿透，报错

### ISSUE THREAD

**Issue by blackness3** [We1eVen/stairspeedtest-docker#1]
因为家里没有公网ip所以使用了 cloudflare tunnel 内网穿透 在家中直接访问192.168：65430   是可以正常使用的。
但是 使用tunnel隧道  https://xxx.xxx.com        报错。请问是什么原因导致的。

后端连接错误！请检查后端运行情况！原因：SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.

![](https://article.biliimg.com/bfs/article/d2add07c786194a57ff82d0e30e755e9d0f89270.png)

**Comment by We1eVen** [comment]
看起来像是https与ws协议之间的安全性要求不匹配，与镜像无关，建议咨询原作者

**Comment by We1eVen** [comment]
看起来像是https与ws协议之间的安全性要求不匹配，与镜像无关，建议咨询原作者
